execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:white_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:16777215,Name:'{"text":"White Bed Hat","color":"white","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:orange_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:16743439,Name:'{"text":"Orange Bed Hat","color":"gold","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:magenta_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:16715715,Name:'{"text":"Magenta Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:light_blue_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:2734079,Name:'{"text":"Light Blue Bed Hat","color":"aqua","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:yellow_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:16765481,Name:'{"text":"Yellow Bed Hat","color":"yellow","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:lime_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:7864105,Name:'{"text":"Lime Bed Hat","color":"green","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:pink_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:15566775,Name:'{"text":"Pink Bed Hat","color":"light_purple","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:gray_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:5990774,Name:'{"text":"Gray Bed Hat","color":"dark_gray","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:light_gray_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:10592673,Name:'{"text":"Light Gray Bed Hat","color":"gray","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:cyan_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:4761521,Name:'{"text":"Cyan Bed Hat","color":"dark_aqua","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:purple_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:7801818,Name:'{"text":"Purple Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:blue_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:3622369,Name:'{"text":"Blue Bed Hat","color":"blue","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:brown_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:7489796,Name:'{"text":"Brown Bed Hat","color":"gold","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:green_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:5997619,Name:'{"text":"Green Bed Hat","color":"dark_green","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:red_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:13180435,Name:'{"text":"Red Bed Hat","color":"red","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}
execute as @s[nbt={ArmorItems:[{},{},{},{id:"minecraft:black_bed",Count:1b}]}] run summon item ~ ~1 ~ {PickupDelay:20s,Item:{id:"leather_helmet",Count:1b,tag:{display:{color:0,Name:'{"text":"Black Bed Hat","color":"black","italic":"false","bold":"true"}'},Unbreakable:1,HideFlags:39}}}

