# replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Red Bed Hat","color":"red","italic":"false","bold":"true"}'}}}]}] armor.head red_bed{display:{Name:'{"text":"Red Bed Hat","color":"red","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}


replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"White Bed Hat","color":"white","italic":"false","bold":"true"}'}}}]}] armor.head white_bed{display:{color:16777215,Name:'{"text":"White Bed Hat","color":"white","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Orange Bed Hat","color":"gold","italic":"false","bold":"true"}'}}}]}] armor.head orange_bed{display:{color:16743439,Name:'{"text":"Orange Bed Hat","color":"gold","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Magenta Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'}}}]}] armor.head magenta_bed{display:{color:16715715,Name:'{"text":"Magenta Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Light Blue Bed Hat","color":"aqua","italic":"false","bold":"true"}'}}}]}] armor.head light_blue_bed{display:{color:2734079,Name:'{"text":"Light Blue Bed Hat","color":"aqua","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Yellow Bed Hat","color":"yellow","italic":"false","bold":"true"}'}}}]}] armor.head yellow_bed{display:{color:16765481,Name:'{"text":"Yellow Bed Hat","color":"yellow","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Lime Bed Hat","color":"green","italic":"false","bold":"true"}'}}}]}] armor.head lime_bed{display:{color:7864105,Name:'{"text":"Lime Bed Hat","color":"green","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Pink Bed Hat","color":"light_purple","italic":"false","bold":"true"}'}}}]}] armor.head pink_bed{display:{color:15566775,Name:'{"text":"Pink Bed Hat","color":"light_purple","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Gray Bed Hat","color":"dark_gray","italic":"false","bold":"true"}'}}}]}] armor.head gray_bed{display:{color:5990774,Name:'{"text":"Gray Bed Hat","color":"dark_gray","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Light Gray Bed Hat","color":"gray","italic":"false","bold":"true"}'}}}]}] armor.head light_gray_bed{display:{color:10592673,Name:'{"text":"Light Gray Bed Hat","color":"gray","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Cyan Bed Hat","color":"dark_aqua","italic":"false","bold":"true"}'}}}]}] armor.head cyan_bed{display:{color:4761521,Name:'{"text":"Cyan Bed Hat","color":"dark_aqua","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Purple Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'}}}]}] armor.head purple_bed{display:{color:7801818,Name:'{"text":"Purple Bed Hat","color":"dark_purple","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Blue Bed Hat","color":"blue","italic":"false","bold":"true"}'}}}]}] armor.head blue_bed{display:{color:3622369,Name:'{"text":"Blue Bed Hat","color":"blue","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Brown Bed Hat","color":"gold","italic":"false","bold":"true"}'}}}]}] armor.head brown_bed{display:{color:7489796,Name:'{"text":"Brown Bed Hat","color":"gold","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Green Bed Hat","color":"dark_green","italic":"false","bold":"true"}'}}}]}] armor.head green_bed{display:{color:5997619,Name:'{"text":"Green Bed Hat","color":"dark_green","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Red Bed Hat","color":"red","italic":"false","bold":"true"}'}}}]}] armor.head red_bed{display:{color:13180435,Name:'{"text":"Red Bed Hat","color":"red","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}
replaceitem entity @a[nbt={Inventory:[{Slot:103b, id:"minecraft:leather_helmet", Count:1b, tag:{display:{Name:'{"text":"Black Bed Hat","color":"black","italic":"false","bold":"true"}'}}}]}] armor.head black_bed{display:{color:0,Name:'{"text":"Black Bed Hat","color":"black","italic":"false","bold":"true"}'},HideFlags:39,AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Slot:"head",Amount:700,Operation:0,UUIDMost:34283,UUIDLeast:116642}]}