execute as @s[scores={BedWhite=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"white_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedOrange=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"orange_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedMagenta=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"magenta_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedLightBlue=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"light_blue_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedYellow=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"yellow_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedLime=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"lime_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedPink=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"pink_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedGray=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"gray_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedLightGray=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"light_gray_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedCyan=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"cyan_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedPurple=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"purple_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedBlue=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"blue_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedBrown=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"brown_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedGreen=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"green_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedRed=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"red_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}
execute as @s[scores={BedBlack=1}] run summon minecraft:armor_stand ^ ^3 ^2 {ArmorItems:[{},{},{},{id:"black_bed",Count:1b}],HandItems:[{},{}],Pose:{Head:[-85.0f, 0.0f, 0.0f]},CustomName:"\"evil_bed\"",NoGravity:1b,NoBasePlate:1b,Invulnerable:1b,Invisible:1b,Tags:["bed","new"]}

summon minecraft:vindicator ^ ^3 ^2 {CustomName:"\"a bed\"",Silent:1b,Tags:["bed","new"],Health:1000,Attributes:[{Name:"generic.maxHealth",Base:1000},{Name:"generic.followRange",Base:500},{Name:"generic.knockbackResistance",Base:0.5f}],NoAI:0b,Invulnerable:0b,PersistenceRequired:1b}

summon armor_stand ^ ^3 ^2 {Invulnerable:1b,NoBasePlate:1,ShowArms:1,CustomName:"\"bed_body\"",NoGravity:1b,HandItems:[{id:"iron_axe",Count:1b},{id:"iron_axe",Count:1b}],Tags:["bed","new"],Pose:{LeftLeg:[0.0f,0.0f,0.0f],RightLeg:[0.0f,0.0f,0.0f],RightArm:[0.0f,0.0f,0.0f],LeftArm:[0.0f,0.0f,0.0f]},Marker:1b}